#!/bin/bash
# Obsługa flagi --date
if [[ "$1" = "--date" || "$1" = "-d" ]]; then
    echo "Dzisiaj jest $(date +%Y-%m-%d)"
# Obsługa flagi --logs bez argumentu
elif [[ "$1" = "--logs" || "$1" = "-l" ]]; then
    for i in {1..100}; do
        filename="log${i}.txt"
        echo "Nazwa pliku: $filename" > "$filename"
        echo "Nazwa skryptu: $0" >> "$filename"
        echo "Data utworzenia: $(date +%Y-%m-%d)" >> "$filename"
    done
# Obsługa flagi --logs z argumentem liczby plików
elif [[ "$1" = "--logs" || "$1" = "-l" ]] && [ "$2" -gt 0 ]; then
    for i in $(seq 1 "$2"); do
        filename="log${i}.txt"
        echo "Nazwa pliku: $filename" > "$filename"
        echo "Nazwa skryptu: $0" >> "$filename"
        echo "Data utworzenia: $(date +%Y-%m-%d)" >> "$filename"
    done
# Obsługa flagi --help
elif [[ "$1" = "--help" || "$1" = "-h" ]]; then
    echo "Dostępne opcje:"
    echo "--date - wyświetla dzisiejszą datę"
    echo "--logs - tworzy 100 plików logx.txt z nazwą, nazwą skryptu i datą utworzenia"
    echo "--logs N - tworzy N plików logx.txt z nazwą, nazwą skryptu i datą utworzenia"


# Obsługa flagi --init
if [ "$1" = "--init" ]; then
  # Klonuj repozytorium do bieżącego katalogu
  git https://github.com/HunT3r-001/lab4 .

  # Dodaj ścieżkę do katalogu bieżącego do zmiennej środowiskowej PATH
  echo "export PATH=\"\${PATH}:$(pwd)\"" >> ~/.bashrc

  # Przeładuj plik .bashrc
  source ~/.bashrc

  echo "Repozytorium zostało sklonowane i ścieżka dodana do zmiennej środowiskowej PATH."
else
  echo "Użycie: skrypt.sh --init"
  exit 1
fi
if [ "$1" = "--init" ]; then
  # Klonuj repozytorium do bieżącego katalogu
  git clone https://github.com/user/repo.git .

  # Dodaj sklonowany katalog do zmiennej środowiskowej PATH
  echo "export PATH=\"\${PATH}:$(pwd)\"" >> ~/.bashrc

  # Przeładuj plik .bashrc
  source ~/.bashrc

  echo "Repozytorium sklonowane i dodane do PATH."
  
elif [ "$1" = "--error" ] && [ "$2" -gt 0 ]; then
  for i in $(seq 1 "$2"); do
    dir_name="error$i"
    mkdir -p "$dir_name"
    filename="$dir_name/error$i.txt"
    echo "Nazwa pliku: $filename" > "$filename"
    echo "Nazwa skryptu: $0" >> "$filename"
    echo "Data utworzenia: $(date +%Y-%m-%d)" >> "$filename"
  done

elif [ "$1" = "-e" ] && [ "$2" -gt 0 ]; then
  for i in $(seq 1 "$2"); do
    dir_name="error$i"
    mkdir -p "$dir_name"
    filename="$dir_name/error$i.txt"
    echo "Nazwa pliku: $filename" > "$filename"
    echo "Nazwa skryptu: $0" >> "$filename"
    echo "Data utworzenia: $(date +%Y-%m-%d)" >> "$filename"
  done

else
  echo "Nieznana flaga lub brak flagi. Użyj --help, aby uzyskać więcej informacji."
fi
