#!/bin/bash
# Obsługa flagi --date
if [ "$1" = "--date" ]; then
    echo "Dzisiaj jest $(date +%Y-%m-%d)"
# Obsługa flagi --logs bez argumentu
elif [ "$1" = "--logs" ]; then
    for i in {1..100}; do
        filename="log${i}.txt"
        echo "Nazwa pliku: $filename" > "$filename"
        echo "Nazwa skryptu: $0" >> "$filename"
        echo "Data utworzenia: $(date +%Y-%m-%d)" >> "$filename"
    done
# Obsługa flagi --logs z argumentem liczby plików
elif [ "$1" = "--logs" ] && [ "$2" -gt 0 ]; then
    for i in $(seq 1 "$2"); do
        filename="log${i}.txt"
        echo "Nazwa pliku: $filename" > "$filename"
        echo "Nazwa skryptu: $0" >> "$filename"
        echo "Data utworzenia: $(date +%Y-%m-%d)" >> "$filename"
    done
# Obsługa flagi --help
elif [ "$1" = "--help" ]; then
    echo "Dostępne opcje:"
    echo "--date - wyświetla dzisiejszą datę"
    echo "--logs - tworzy 100 plików logx.txt z nazwą, nazwą skryptu i datą utworzenia"
    echo "--logs N - tworzy N plików logx.txt z nazwą, nazwą skryptu i datą utworzenia"
