#!/bin/bash
# Obsługa flagi --date
if [ "$1" = "--date" ]; then
    echo "Dzisiaj jest $(date +%Y-%m-%d)"
# Obsługa flagi --logs bez argumentu
elif [ "$1" = "--logs" ]; then
    for i in {1..100}; do
        filename="log${i}.txt"
        echo "Nazwa pliku: $filename" > "$filename"
        echo "Nazwa skryptu: $0" >> "$filename"
        echo "Data utworzenia: $(date +%Y-%m-%d)" >> "$filename"
    done
